name: 🐛 Bug Report (Coding Agent)
description: Report a bug for the Coding Agent to fix
title: "[Bug]: "
labels: ["bug", "coding-agent"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This will be automatically assigned to the Coding Agent (@copilot) for investigation and fixing.
        
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop or paste screenshots here...
    validations:
      required: false
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment information
      placeholder: |
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 22]
        - OS: [e.g. macOS, Windows, Linux]
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
    validations:
      required: false