name: 🤖 Coding Agent Task
description: Create a task for the GitHub Copilot Coding Agent
title: "[Coding Agent]: "
labels: ["coding-agent"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a task for the Coding Agent! This template will automatically assign the issue to @copilot.
        
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Describe what you want the Coding Agent to accomplish
      placeholder: Please provide a clear description of the task...
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what success looks like for this task
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: Any additional information that might help...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true