---
name: Tag rajbos on new issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  tag-rajbos:
    # Only run on the main repository, not on forks
    if: github.repository == 'devops-actions/github-copilot-premium-reqs-usage'
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Tag rajbos
        uses: devops-actions/issue-comment-tag@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: rajbos
